name: 'Get and Alias Vercel Preview URL'
description: 'Get preview URL of a Vercel deployment and alias it automatically'
branding:
  icon: activity
  color: gray-dark
author: 'justInCaseTechnologies'
inputs:
  vercel_access_token:
    description: 'https://vercel.com/docs/rest-api#introduction/api-basics/authentication/creating-an-access-token'
    required: true
  vercel_project_id:
    description: 'Get your Project ID from project settings in Vercel management console'
    required: true
  vercel_team_id:
    description: 'https://vercel.com/docs/rest-api#introduction/api-basics/authentication/accessing-resources-owned-by-a-team'
    required: false
  alias_template:
    description: 'template of alias preview url. eg: {random}.e2e-test.mysite.com'
    required: false
  token:
    description: 'https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret'
    required: false
    default: ${{ github.token }}
  retry_times:
    description: 'Max retry times for waiting deployment(default: 18)'
    required: false
    default: 18
  interval:
    description: 'Time span (ms) waiting between requests to the Vercel API(default: 10000ms)'
    required: false
    default: 10000
  fail_when_cancelled:
    description: 'Automatically fail if deployment of Vercel is cancelled(default: true)'
    required: false
    default: true
  commit_sha:
    description: 'sha of commit which triggered Vercel Preview deployment. It is useful when workflow is triggered by issue_comment.'
    required: false
outputs:
  preview_url_alias:
    description: 'Alias of Vercel Preview URL'
  preview_url_origin:
    description: 'Original Vercel Preview URL'
  status:
    description: 'Status of the Vercel deployment'
runs:
  using: 'node16'
  main: 'dist/index.js'
