name: 'event-test'
on: [deployment_status]

jobs:
  event_test:
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'Preview'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Vercel's Alias Preview URL
        id: alias-preview-url
        uses: ./
        with:
          vercel_access_token: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          alias_template: '{random}.vercel-preview-url-alias.joinsure.tech'

      - name: Echo preview
        run: |
          echo "${{ steps.alias-preview-url.outputs.preview_url_origin }} vs ${{ steps.alias-preview-url.outputs.preview_url_alias }}"
          echo "${{ steps.alias-preview-url.outputs.status }}"
